### PR TITLE
DataFrame print table, Main menu and CMake copy CSV files to build directory

### PR DESCRIPTION
**Pull request by andrewlod**
In this pull requested I have added a couple features:
- Main menu with 8 options, including read, save and show table for grades and students, add and remove students
- Pretty print DataFrame table
- Export GradeBook data structures to DataFrames
- CMakeLists.txt copy CSV files to build directory

### CODE REVIEW

**Comment by gbowne1** [comment]
@andrewlod this looks like you only shipped the build and some .csv's not the update(s).

**Review by gbowne1 — APPROVED** [review]
Merging this as is.  Appears to be missing a few things.

But the .csv's appear to have headers for tables.

Approving for merge & merging.

**Comment by andrewlod** [comment]
My apologies for that. Usually I would just do `git add .` and all changes, including modifications and deletions would be included, but for some reason, they were not this time. I have included the changes in a new pull request.

**Comment by andrewlod** [comment]
> Do we make separate testdata for individual tests, use our gradebook program to help the teacher input the grades/scores, or?

I suppose test grades could work the same way as assignment grades, where there is a CSV file, say, `testgrades.csv` with columns `test_id,student_id,grade`, and another CSV file `testdata.csv` with columns `test_id,name/description,class_id`.

Now for the teacher to update grades efficiently, it would be a lot easier if there was an actual UI (web or even Desktop) where a teacher could easily jump from one student to another (using arrow keys or the mouse, for example), in order to post grades. Another solution would be: GradeBook knows all students, and students could be linked to classes (CSV `studentclasses.csv` with columns `student_id,class_id,semester`), and tests are also linked to classes. Whenever a teacher wants to fill in the grades of an ungraded test, GradeBook could query all students of the class the test was applied and ask the grade, one by one, without the teacher having to type the name (or ID) of each student, just the grades. Does that make sense?

**Comment by gbowne1** [comment]
Yeah that does make sense. I originally thought about some sort of UI when I made this program as well  as intended for it to actually be used.

I don't know about a Web UI but certainly something useable could be made for the program. 

Some sense of security needs to be had too so that someone couldn't get in and change grades scores etc without authorization which could be just username and password and a verification, maybe a couple levels deep.

**Comment by andrewlod** [comment]
Since we are thinking about authentication and UI, maybe it would make sense to make it a server (i.e. API) with a front-end. I have some experience with [CPPRestSDK](https://github.com/microsoft/cpprestsdk) and it is cross-platform. There are some advantages to this approach, where people from multiple devices can connect to the service. Alternatively, if the goal is to have a local application only, it is possible to proceed with an approach without a server (like the current state of the project).

As for UI libraries, I have worked with [openFrameworks](https://openframeworks.cc) and [wxWidgets](https://www.wxwidgets.org). Maybe the second one fits better in GUIs, but I am not completely sure. There is also [QT](https://www.qt.io/product), but I have never used it.

**Comment by gbowne1** [comment]
I would be concerned with making the program capable.  ie features first before we actually go down the UI route.. but yes, UI.  I am completely ok with a text based UI <think fancy text screens> akin to 16 bit early 32 bit DOS applications. 

API would be good too.

**Pull request merged**
